//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::email_address::Entity as EmailAddress;
#[cfg(feature = "entity")]
pub use super::entity::Entity;
pub use super::user::Entity as User;
