[package]
name = "shield-credentials"
description = "Credentials provider for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
shield = { path = "../../core/shield", version = "0.0.4" }
