[package]
name = "shield-sea-orm"
description = "SeaORM storage for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
entity = []
all-methods = [
    # "method-credentials",
    "method-email",
    "method-oauth",
    "method-oidc",
    # "method-webauthn",
]
# method-credentials = ["dep:shield-credentials"]
# method-email = ["dep:shield-email"]
# method-credentials = []
method-email = []
method-oauth = ["dep:shield-oauth"]
method-oidc = ["dep:shield-oidc"]
# method-webauthn = ["dep:shield-webauthn"]
utoipa = ["dep:utoipa", "shield/utoipa"]

[dependencies]
async-trait.workspace = true
chrono.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
secrecy.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
shield.workspace = true
# shield-credentials = { workspace = true, optional = true }
# shield-email = { workspace = true, optional = true }
shield-oauth = { workspace = true, optional = true }
shield-oidc = { workspace = true, optional = true }
# shield-webauthn = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }
