[package]
name = "shield-dioxus"
description = "Dioxus integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
server = ["dioxus/server"]

[dependencies]
async-trait.workspace = true
dioxus = { workspace = true, features = ["fullstack", "router"] }
serde_json.workspace = true
shield.workspace = true
