[package]
name = "shield-leptos-axum"
description = "Leptos Axum integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
utoipa = ["shield/utoipa", "shield-axum/utoipa"]

[dependencies]
async-trait.workspace = true
leptos.workspace = true
leptos_axum.workspace = true
shield.workspace = true
shield-axum.workspace = true
shield-leptos.workspace = true
