[package]
name = "shield-leptos-axum"
description = "Leptos Axum integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
leptos.workspace = true
leptos_axum.workspace = true
shield = { path = "../../core/shield", version = "0.0.2" }
shield-axum = { path = "../../integrations/shield-axum", version = "0.0.2" }
shield-leptos = { path = "../../integrations/shield-leptos", version = "0.0.2" }
