[package]
name = "shield-axum"
description = "Axum integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
utoipa = ["dep:utoipa", "shield/utoipa"]

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
shield.workspace = true
shield-tower.workspace = true
utoipa = { workspace = true, features = ["axum_extras"], optional = true }
