[package]
name = "shield-axum"
description = "Axum integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
shield = { path = "../../core/shield" }
shield-tower = { path = "../shield-tower" }
