[package]
name = "shield-axum"
description = "Axum integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
shield = { path = "../../core/shield", version = "0.0.4" }
shield-tower = { path = "../shield-tower", version = "0.0.4" }
utoipa = { workspace = true, features = ["axum_extras"], optional = true }

[features]
default = []
utoipa = ["dep:utoipa"]
