[package]
name = "shield-dioxus-axum"
description = "Dioxus Axum integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
utoipa = ["shield-axum/utoipa"]

[dependencies]
anyhow.workspace = true
dioxus-server.workspace = true
shield.workspace = true
shield-axum.workspace = true
shield-dioxus.workspace = true
