[package]
name = "shield-dioxus-axum"
description = "Dioxus Axum integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
utoipa = ["shield-axum/utoipa"]

[dependencies]
async-trait.workspace = true
dioxus = { workspace = true, features = ["server"] }
shield.workspace = true
shield-axum.workspace = true
shield-dioxus.workspace = true
