[package]
name = "shield-webauthn"
description = "WebAuthn method for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
shield.workspace = true
