[package]
name = "shield-memory"
description = "In-memory storage for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
all-methods = [
    # "method-credentials",
    # "method-email",
    # "method-oauth",
    "method-oidc",
    # "method-webauthn",
]
# method-credentials = ["dep:shield-credentials"]
# method-email = ["dep:shield-email"]
# method-oauth = ["dep:shield-oauth"]
method-oidc = ["dep:shield-oidc"]

[dependencies]
async-trait.workspace = true
serde.workspace = true
shield.workspace = true
# shield-credentials = { workspace = true, optional = true }
# shield-email = { workspace = true, optional = true }
# shield-oauth = { workspace = true, optional = true }
shield-oidc = { workspace = true, optional = true }
# shield-webauthn = { workspace = true, optional = true }
uuid = { workspace = true, features = ["v4"] }
# method-webauthn = ["dep:shield-webauthn"]
