[package]
name = "shield-memory"
description = "In-memory storage for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
shield = { path = "../../core/shield", version = "0.0.4" }
# shield-credentials = { path = "../../providers/shield-credentials", version = "0.0.2", optional = true }
# shield-email = { path = "../../providers/shield-email", version = "0.0.2", optional = true }
# shield-oauth = { path = "../../providers/shield-oauth", version = "0.0.2", optional = true }
shield-oidc = { path = "../../providers/shield-oidc", version = "0.0.4", optional = true }
# shield-webauthn = { path = "../../providers/shield-webauthn", version = "0.0.2", optional = true }
uuid = { workspace = true, features = ["v4"] }

[features]
default = []
all-providers = [
    # "provider-credentials",
    # "provider-email",
    # "provider-oauth",
    "provider-oidc",
    # "provider-webauthn",
]
# provider-credentials = ["dep:shield-credentials"]
# provider-email = ["dep:shield-email"]
# provider-oauth = ["dep:shield-oauth"]
provider-oidc = ["dep:shield-oidc"]
# provider-webauthn = ["dep:shield-webauthn"]
