[package]
name = "shield-memory"
description = "In-memory storage for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
shield = { path = "../../core/shield" }
shield-credentials = { path = "../../providers/shield-credentials", optional = true }
shield-email = { path = "../../providers/shield-email", optional = true }
shield-oauth = { path = "../../providers/shield-oauth", optional = true }
shield-oidc = { path = "../../providers/shield-oidc", optional = true }
shield-webauthn = { path = "../../providers/shield-webauthn", optional = true }
uuid = { workspace = true, features = ["v4"] }

[features]
default = []
all-providers = [
    "provider-credentials",
    "provider-email",
    "provider-oauth",
    "provider-oidc",
    "provider-webauthn",
]
provider-credentials = ["dep:shield-credentials"]
provider-email = ["dep:shield-email"]
provider-oauth = ["dep:shield-oauth"]
provider-oidc = ["dep:shield-oidc"]
provider-webauthn = ["dep:shield-webauthn"]
