// This file is auto-generated by @hey-api/openapi-ts
import { type DefaultError, type UseMutationOptions, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen.js';
import {
    type Options,
    callAction,
    getActionForms,
    getCurrentUser,
    signInCallbackOidc,
    signInOidc,
    signOutOidc,
} from '../sdk.gen.js';
import type {
    CallActionData,
    CallActionError,
    GetActionFormsData,
    GetCurrentUserData,
    SignInCallbackOidcData,
    SignInOidcData,
    SignOutOidcData,
} from '../types.gen.js';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    },
];

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
    } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getActionFormsQueryKey = (options: Options<GetActionFormsData>) =>
    createQueryKey('getActionForms', options);

/**
 * Get action forms
 *
 * Get action forms.
 */
export const getActionFormsOptions = (options: Options<GetActionFormsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getActionForms({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: getActionFormsQueryKey(options),
    });
};

export const signInCallbackOidcQueryKey = (options: Options<SignInCallbackOidcData>) =>
    createQueryKey('signInCallbackOidc', options);

/**
 * Sign in callback for OpenID Connect
 *
 * Sign in callback for OpenID Connect.
 */
export const signInCallbackOidcOptions = (options: Options<SignInCallbackOidcData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await signInCallbackOidc({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: signInCallbackOidcQueryKey(options),
    });
};

/**
 * Sign in with OpenID Connect
 *
 * Sign in with OpenID Connect.
 */
export const signInOidcMutation = (
    options?: Partial<Options<SignInOidcData>>,
): UseMutationOptions<unknown, DefaultError, Options<SignInOidcData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SignInOidcData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signInOidc({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

/**
 * Sign out with OpenID Connect
 *
 * Sign out with OpenID Connect.
 */
export const signOutOidcMutation = (
    options?: Partial<Options<SignOutOidcData>>,
): UseMutationOptions<unknown, DefaultError, Options<SignOutOidcData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SignOutOidcData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signOutOidc({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) =>
    createQueryKey('getCurrentUser', options);

/**
 * Get current user
 *
 * Get the current user account.
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCurrentUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: getCurrentUserQueryKey(options),
    });
};

/**
 * Call action
 *
 * Call an action.
 */
export const callActionMutation = (
    options?: Partial<Options<CallActionData>>,
): UseMutationOptions<unknown, CallActionError, Options<CallActionData>> => {
    const mutationOptions: UseMutationOptions<unknown, CallActionError, Options<CallActionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await callAction({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};
