// This file is auto-generated by @hey-api/openapi-ts
import { client } from './client.gen.js';
import {
    type Client,
    type Options as Options2,
    type TDataShape,
    urlSearchParamsBodySerializer,
} from './client/index.js';
import type {
    CallActionData,
    CallActionErrors,
    GetActionFormsData,
    GetActionFormsErrors,
    GetActionFormsResponses,
    GetCurrentUserData,
    GetCurrentUserErrors,
    GetCurrentUserResponses,
    SignInCallbackOidcData,
    SignInCallbackOidcErrors,
    SignInOidcData,
    SignInOidcErrors,
    SignOutOidcData,
    SignOutOidcErrors,
} from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get action forms
 *
 * Get action forms.
 */
export const getActionForms = <ThrowOnError extends boolean = false>(
    options: Options<GetActionFormsData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetActionFormsResponses, GetActionFormsErrors, ThrowOnError>({
        url: '/api/auth/forms/{actionId}',
        ...options,
    });
};

/**
 * Sign in callback for OpenID Connect
 *
 * Sign in callback for OpenID Connect.
 */
export const signInCallbackOidc = <ThrowOnError extends boolean = false>(
    options: Options<SignInCallbackOidcData, ThrowOnError>,
) => {
    return (options.client ?? client).get<unknown, SignInCallbackOidcErrors, ThrowOnError>({
        url: '/api/auth/oidc/sign-in-callback/{providerId}',
        ...options,
    });
};

/**
 * Sign in with OpenID Connect
 *
 * Sign in with OpenID Connect.
 */
export const signInOidc = <ThrowOnError extends boolean = false>(options: Options<SignInOidcData, ThrowOnError>) => {
    return (options.client ?? client).post<unknown, SignInOidcErrors, ThrowOnError>({
        url: '/api/auth/oidc/sign-in/{providerId}',
        ...options,
    });
};

/**
 * Sign out with OpenID Connect
 *
 * Sign out with OpenID Connect.
 */
export const signOutOidc = <ThrowOnError extends boolean = false>(options: Options<SignOutOidcData, ThrowOnError>) => {
    return (options.client ?? client).post<unknown, SignOutOidcErrors, ThrowOnError>({
        url: '/api/auth/oidc/sign-out/{providerId}',
        ...options,
    });
};

/**
 * Get current user
 *
 * Get the current user account.
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
    options?: Options<GetCurrentUserData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
        url: '/api/auth/user',
        ...options,
    });
};

/**
 * Call action
 *
 * Call an action.
 */
export const callAction = <ThrowOnError extends boolean = false>(options: Options<CallActionData, ThrowOnError>) => {
    return (options.client ?? client).post<unknown, CallActionErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/api/auth/{methodId}/{actionId}/{providerId}',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers,
        },
    });
};
