[package]
name = "shield-oidc"
description = "OpenID Connect method for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.cargo-machete]
ignored = ["oauth2", "serde_json"]

[features]
default = []
native-tls = ["oauth2/native-tls", "openidconnect/native-tls"]
rustls-tls = ["oauth2/rustls-tls", "openidconnect/native-tls"]

[dependencies]
async-trait.workspace = true
bon.workspace = true
chrono.workspace = true
oauth2 = { version = "5.0.0", default-features = false, features = [
    "pkce-plain",
] }
openidconnect = { version = "4.0.0", default-features = false, features = [
    "reqwest",
] }
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
shield.workspace = true
tracing.workspace = true
