[package]
name = "shield-leptos-actix"
description = "Leptos Actix integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
leptos.workspace = true
leptos_actix.workspace = true
shield.workspace = true
shield-actix.workspace = true
shield-leptos.workspace = true
