//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::email_address::Entity as EmailAddress;
pub use super::email_auth_token::Entity as EmailAuthToken;
pub use super::oauth_provider::Entity as OauthProvider;
pub use super::oauth_provider_connection::Entity as OauthProviderConnection;
pub use super::oidc_provider::Entity as OidcProvider;
pub use super::oidc_provider_connection::Entity as OidcProviderConnection;
pub use super::user::Entity as User;
