//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "oauth_provider_pkce_code_challenge"
)]
pub enum OauthProviderPkceCodeChallenge {
    #[sea_orm(string_value = "none")]
    None,
    #[sea_orm(string_value = "plain")]
    Plain,
    #[sea_orm(string_value = "s256")]
    S256,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "oauth_provider_type"
)]
pub enum OauthProviderType {
    #[sea_orm(string_value = "custom")]
    Custom,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "oauth_provider_visibility"
)]
pub enum OauthProviderVisibility {
    #[sea_orm(string_value = "private")]
    Private,
    #[sea_orm(string_value = "public")]
    Public,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "oidc_provider_pkce_code_challenge"
)]
pub enum OidcProviderPkceCodeChallenge {
    #[sea_orm(string_value = "none")]
    None,
    #[sea_orm(string_value = "plain")]
    Plain,
    #[sea_orm(string_value = "s256")]
    S256,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "oidc_provider_type")]
pub enum OidcProviderType {
    #[sea_orm(string_value = "custom")]
    Custom,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "oidc_provider_visibility"
)]
pub enum OidcProviderVisibility {
    #[sea_orm(string_value = "private")]
    Private,
    #[sea_orm(string_value = "public")]
    Public,
}
