[package]
name = "shield-workos"
description = "WorkOS method for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
bon.workspace = true
serde.workspace = true
serde_json.workspace = true
shield.workspace = true
tracing.workspace = true
workos-sdk = "0.3.0"
