[package]
name = "shield"
description = "Web authentication for Rust."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
utoipa = ["dep:utoipa"]

[dependencies]
async-trait.workspace = true
bon.workspace = true
chrono = { workspace = true, features = ["serde"] }
convert_case = "0.8.0"
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
utoipa = { workspace = true, optional = true }
