[package]
name = "shield-oauth"
description = "OAuth provider for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
oauth2 = { version = "5.0.0", default-features = false, features = ["reqwest"] }
shield = { path = "../../core/shield", version = "0.0.4" }

[features]
default = ["rustls-tls"]
native-tls = ["oauth2/native-tls"]
rustls-tls = ["oauth2/rustls-tls"]
