[package]
name = "shield-leptos"
description = "Leptos integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
leptos.workspace = true
serde.workspace = true
shield = { path = "../../core/shield", version = "0.0.2" }
