[package]
name = "shield-actix"
description = "Actix integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
actix-session.workspace = true
actix-utils.workspace = true
actix-web.workspace = true
shield = { path = "../../core/shield", version = "0.0.3" }
