[package]
name = "shield-oidc"
description = "OpenID Connect provider for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
oauth2 = { version = "4.4.2", features = ["pkce-plain"] }
openidconnect = "3.5.0"
shield = { path = "../../core/shield", version = "0.0.2" }
tracing.workspace = true
