[package]
name = "shield-oauth"
description = "OAuth method for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
oauth2 = { version = "5.0.0", default-features = false, features = ["reqwest"] }
shield.workspace = true

[features]
default = []
native-tls = ["oauth2/native-tls"]
rustls-tls = ["oauth2/rustls-tls"]
