[package]
name = "shield-sqlx"
description = "SQLx storage for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
shield = { path = "../../core/shield", version = "0.0.4" }
