name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@c18f3b7315df398b6af8d03f823e31daeda63114
        with:
            enable-test: false
            target: wasm32-unknown-unknown

    test:
        name: Test
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql
                ports:
                    - 13306:3306
                env:
                    MYSQL_ROOT_PASSWORD: shield
                    MYSQL_USER: shield
                    MYSQL_PASSWORD: shield
                    MYSQL_DATABASE: shield

            postgresql:
                image: postgres
                ports:
                    - 15432:5432
                env:
                    POSTGRES_USER: shield
                    POSTGRES_PASSWORD: shield
                    POSTGRES_DB: shield

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
              with:
                  target: wasm32-unknown-unknown
                  components: rust-src

            - name: Test
              run: cargo test --locked --release
