name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

env:
    RUSTFLAGS: '-Dwarnings'

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: clippy, rustfmt
                  target: wasm32-unknown-unknown

            - name: Install Cargo Binary Install
              uses: cargo-bins/cargo-binstall@main

            - name: Install crates
              run: cargo binstall -y --force cargo-deny cargo-machete cargo-sort

            - name: Lint
              run: cargo clippy --locked

            - name: Check dependencies
              run: cargo deny check

            - name: Check unused dependencies
              run: cargo machete

            - name: Check manifest formatting
              run: cargo sort --workspace --check

            - name: Check formatting
              run: cargo fmt --all --check

    test:
        name: Test
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql
                ports:
                    - 13306:3306
                env:
                    MYSQL_ROOT_PASSWORD: shield
                    MYSQL_USER: shield
                    MYSQL_PASSWORD: shield
                    MYSQL_DATABASE: shield

            postgresql:
                image: postgres
                ports:
                    - 15432:5432
                env:
                    POSTGRES_USER: shield
                    POSTGRES_PASSWORD: shield
                    POSTGRES_DB: shield

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: clippy, rustfmt
                  target: wasm32-unknown-unknown

            - name: Install Cargo Binary Install
              uses: cargo-bins/cargo-binstall@main

            - name: Install crates
              run: cargo binstall -y sea-orm-cli

            - name: Test
              run: cargo test --locked
