name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@dc2442c27ef9f920a1a889ec94e615b419b491b2 # v1.0.1
        with:
            enable-test: false
            target: wasm32-unknown-unknown

    test:
        name: Test
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql
                ports:
                    - 13306:3306
                env:
                    MYSQL_ROOT_PASSWORD: shield
                    MYSQL_USER: shield
                    MYSQL_PASSWORD: shield
                    MYSQL_DATABASE: shield

            postgresql:
                image: postgres
                ports:
                    - 15432:5432
                env:
                    POSTGRES_USER: shield
                    POSTGRES_PASSWORD: shield
                    POSTGRES_DB: shield

        steps:
            - name: Checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
              with:
                  target: wasm32-unknown-unknown
                  components: rust-src

            - name: Test
              run: cargo test --locked --release
