name: Labels

on:
    workflow_dispatch:

permissions:
    contents: read
    issues: write

jobs:
    labels:
        name: Labels
        uses: RustForWeb/.github/.github/workflows/labels.yml@dc2442c27ef9f920a1a889ec94e615b419b491b2 # v1.0.1
