name: Labels

on:
    workflow_dispatch:

permissions:
    contents: read
    issues: write

jobs:
    labels:
        name: Labels
        uses: RustForWeb/.github/.github/workflows/labels.yml@8a0ce4333fd134d177f151cba9b768f041f43601 # v1.0.3
