name: Labels

on:
    workflow_dispatch:

permissions:
    contents: read
    issues: write

jobs:
    labels:
        name: Labels
        uses: RustForWeb/.github/.github/workflows/labels.yml@c18f3b7315df398b6af8d03f823e31daeda63114
