name: Website

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write
    pages: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    book:
        name: Book
        uses: RustForWeb/.github/.github/workflows/book.yml@c18f3b7315df398b6af8d03f823e31daeda63114
        with:
            combine: false
